# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def create_fibonacci(max)
  fibonacci = [1,2]
  until fibonacci[-1] > max
    fibonacci << fibonacci[-1] + fibonacci[-2]
  end
  fibonacci
end

def even_fibonacci(max)
  fibonacci = create_fibonacci(max)
  fibonacci.inject([]) do |result, element|
    result << element if element % 2 == 0 && element < max
    result
  end
end

def sum(max)
  even_fibonacci(max).inject(:+)
end

sum(4000000) #4613732
