# This file was generated by the `rspec --init` command.
RSpec.configure do |config|
  #Dir["./project_euler/*.rb"].each {|f| require f}
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

end
